version: "3"

services:
  app:
    build: .
    command: npm start
    container_name: spaceX
    ports:
      - 3003:3003
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: